// Generated by CoffeeScript 1.8.0
(function() {
  var require;

  require = window.require;

  describe('The {{name}} Model', function() {
    var {{name}};
    {{name}} = require('models/{{path}}');
    return it('can noop', function() {});
  });

}).call(this);
